question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The common software-programming acronym I18N comes from the term Interlocalization.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The very first recorded computer bug was a moth found inside a Harvard Mark II computer.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Windows NT is a monolithic kernel.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The open source program Redis is a relational database server.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "In most programming languages, the operator ++ is equivalent to the statement += 1.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
     "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "A Boolean value of 0 represents which of these words?", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                                      "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}]
